name: cursor-schedule

on:
  schedule:
    - cron: "0 0 */10 * *" # 每10天 UTC 0:00
  workflow_dispatch: # 保留手动触发用于测试

env:
  ACCOUNTS_NUMBER: ${{ vars.CURSOR_ACCOUNTS_NUMBER || 2 }} # 默认 2 个账号

jobs:
  register:
    runs-on: windows-latest
    env:
      HIDE_ACCOUNT_INFO: "true"
    steps:
      - uses: actions/checkout@v3

      - name: Install requirements
        run: |
          pip3 install -r ./requirements.txt

      - name: Run registration
        run: |
          python3 ./cursor_register.py --oneapi --oneapi_url "${{ secrets.CURSOR_ONEAPI_URL }}" --oneapi_token "${{ secrets.CURSOR_ONEAPI_TOKEN }}" --oneapi_channel_url "${{ secrets.CURSOR_CHANNEL_URL }}" --number ${{ env.ACCOUNTS_NUMBER }}
